# Generated by Django 2.1.1 on 2018-10-13 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='info',
        ),
    ]
