# Generated by Django 2.1.1 on 2018-10-16 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0002_remove_publication_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, null=True, unique=True),
        ),
    ]
