# Generated by Django 2.1.1 on 2018-10-10 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(default='Dhaka', max_length=120),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(default='Bangladesh', max_length=120),
        ),
    ]
