# Generated by Django 2.1.1 on 2018-10-29 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0003_address_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address_line_2',
        ),
        migrations.RemoveField(
            model_name='address',
            name='state',
        ),
        migrations.AddField(
            model_name='address',
            name='full_name',
            field=models.CharField(default='shamsul', max_length=155),
            preserve_default=False,
        ),
    ]
