# Generated by Django 2.1.1 on 2018-10-29 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0004_auto_20181029_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='phone',
            field=models.CharField(default='017', max_length=15),
            preserve_default=False,
        ),
    ]
