# Generated by Django 2.1.1 on 2018-10-24 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_auto_20181024_2150'),
        ('orders', '0014_auto_20181024_2150'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Items',
        ),
    ]
