# Generated by Django 2.1.1 on 2018-10-26 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rent',
            old_name='cart',
            new_name='rent_cart',
        ),
    ]
