# Generated by Django 2.1.1 on 2018-10-26 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_auto_20181026_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentcart',
            name='sub_total',
        ),
    ]
