# Generated by Django 2.1.1 on 2018-10-26 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0003_remove_rentcart_sub_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentcart',
            name='price',
        ),
    ]
