# Generated by Django 2.1.1 on 2018-10-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0005_auto_20181027_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='rent_id',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
