# Generated by Django 2.1.1 on 2018-10-27 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0006_rent_rent_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rent',
            old_name='rent_id',
            new_name='order_id',
        ),
    ]
