# Generated by Django 2.1.1 on 2018-10-27 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0007_auto_20181027_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
