# Generated by Django 2.1.1 on 2018-10-27 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0008_rent_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
