# Generated by Django 2.1.1 on 2018-10-27 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0009_auto_20181027_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='receive_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
