# Generated by Django 2.1.1 on 2018-10-28 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0002_auto_20181016_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='keyword',
            field=models.CharField(help_text='Enter Tag keyword', max_length=155, unique=True),
        ),
    ]
