# Generated by Django 2.1.1 on 2018-10-18 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20181018_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
