# Generated by Django 2.1.1 on 2018-10-16 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20181016_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='keyword',
            field=models.CharField(help_text='Enter Tag keyword', max_length=155, unique=True),
        ),
    ]
