# Generated by Django 2.1.1 on 2018-10-29 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_requestpayment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestpayment',
            name='phone',
            field=models.CharField(default='017', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requestpayment',
            name='status',
            field=models.CharField(choices=[('unpaid', 'UnPaid'), ('paid', 'Paid'), ('pending', 'Pending'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='unpaid', max_length=120),
        ),
    ]
