# Generated by Django 2.1.1 on 2018-10-30 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto_20181030_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestpayment',
            name='payment_by',
            field=models.CharField(choices=[('bkash', 'Bkash'), ('rocket', 'Rocket'), ('cash', 'Cash')], default='', max_length=120),
        ),
    ]
