# Generated by Django 2.1.1 on 2018-10-01 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter Author name', max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='Author/img')),
                ('bio', models.TextField()),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter Book Name', max_length=255)),
                ('publish_date', models.DateField()),
                ('last_edition_publish', models.DateField(blank=True, null=True)),
                ('regular_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('descriptions', models.TextField()),
                ('rent_charge', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('image', models.ImageField(blank=True, upload_to='Book/img')),
                ('is_stock', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.BookAuthor')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('tag', models.ManyToManyField(to='tag.Tag')),
            ],
        ),
    ]
