# Generated by Django 2.1.1 on 2018-10-10 16:15

from django.db import migrations, models
import django.db.models.deletion
import product.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publication', '0001_initial'),
        ('author', '0001_initial'),
        ('category', '0001_initial'),
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter Book Name', max_length=255)),
                ('publish_date', models.CharField(help_text='Year eg. 1998 , 2018', max_length=4)),
                ('total_pages', models.PositiveIntegerField(blank=True, null=True)),
                ('regular_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('descriptions', models.TextField()),
                ('rent_charge', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('image', models.ImageField(blank=True, upload_to=product.models.upload_book_image_path)),
                ('is_old', models.BooleanField(default=True)),
                ('is_stock', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('is_rent_available', models.BooleanField(default=True)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='author.BookAuthor')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publication.Publication')),
                ('tag', models.ManyToManyField(to='tag.Tag')),
            ],
            options={
                'ordering': ['-timeStamp'],
            },
        ),
    ]
