# Generated by Django 2.1.1 on 2018-10-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booklist',
            name='publish_date',
        ),
        migrations.AddField(
            model_name='booklist',
            name='country',
            field=models.CharField(choices=[('bangladesh', 'Bangladesh'), ('india', 'India'), ('japan', 'Japan'), ('usa', 'USA'), ('uk', 'UK'), ('others', 'Others')], default='bangladesh', max_length=20),
        ),
        migrations.AddField(
            model_name='booklist',
            name='edition',
            field=models.CharField(blank=True, help_text='Year eg. 1st Edition, 2018', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='booklist',
            name='isbn',
            field=models.CharField(blank=True, help_text='eg. 9847034301595', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='booklist',
            name='language',
            field=models.CharField(choices=[('bengali', 'Bengali'), ('english', 'English'), ('Arabic', 'Arabic'), ('hindi', 'Hindi'), ('spanish', 'Spanish'), ('german', 'German'), ('french', 'French'), ('italian', 'Italian'), ('others', 'Others')], default='bengali', max_length=20),
        ),
    ]
