# Generated by Django 2.1.1 on 2018-10-02 16:08

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookauthor',
            name='image',
            field=models.ImageField(blank=True, upload_to=product.models.upload_author_image_path),
        ),
        migrations.AlterField(
            model_name='booklist',
            name='image',
            field=models.ImageField(blank=True, upload_to=product.models.upload_book_image_path),
        ),
    ]
