# Generated by Django 2.1.1 on 2018-10-01 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklist',
            name='last_edition_publish',
            field=models.CharField(blank=True, help_text='Year eg. 1998 , 2018', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='booklist',
            name='publish_date',
            field=models.CharField(help_text='Year eg. 1998 , 2018', max_length=4),
        ),
    ]
