# Generated by Django 2.1.1 on 2018-09-29 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20180929_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklist',
            name='last_edition_publish',
            field=models.DateField(blank=True, null=True),
        ),
    ]
