# Generated by Django 2.1.1 on 2018-10-05 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_booklist_is_rent_available'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booklist',
            options={'ordering': ['-timeStamp']},
        ),
        migrations.RemoveField(
            model_name='booklist',
            name='last_edition_publish',
        ),
        migrations.AddField(
            model_name='booklist',
            name='is_old',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='booklist',
            name='total_pages',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
