# Generated by Django 2.1.1 on 2018-09-29 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20180929_1244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookauthor',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='booklist',
            old_name='title',
            new_name='name',
        ),
    ]
