# Generated by Django 2.1.1 on 2018-10-16 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0002_remove_publication_info'),
        ('product', '0004_auto_20181013_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklist',
            name='translator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translator', to='publication.Publication'),
        ),
        migrations.AlterField(
            model_name='booklist',
            name='is_old',
            field=models.BooleanField(default=False),
        ),
    ]
