# Generated by Django 2.1.1 on 2018-10-19 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20181016_1837'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booklist',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RenameField(
            model_name='booklist',
            old_name='timeStamp',
            new_name='timestamp',
        ),
    ]
