# Generated by Django 2.1.1 on 2018-10-19 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
        ('product', '0012_auto_20181020_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklist',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='review.Review'),
        ),
    ]
