# Generated by Django 2.1.1 on 2018-10-19 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_booklist_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booklist',
            name='review',
        ),
    ]
