# Generated by Django 2.1.1 on 2018-10-27 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0005_auto_20181016_1550'),
        ('publication', '0004_auto_20181016_1149'),
        ('category', '0004_auto_20181016_1550'),
        ('product', '0015_booklist_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booklist',
            name='author',
        ),
        migrations.AddField(
            model_name='booklist',
            name='author',
            field=models.ManyToManyField(to='author.BookAuthor'),
        ),
        migrations.RemoveField(
            model_name='booklist',
            name='category',
        ),
        migrations.AddField(
            model_name='booklist',
            name='category',
            field=models.ManyToManyField(to='category.Category'),
        ),
        migrations.RemoveField(
            model_name='booklist',
            name='publication',
        ),
        migrations.AddField(
            model_name='booklist',
            name='publication',
            field=models.ManyToManyField(to='publication.Publication'),
        ),
    ]
