# Generated by Django 2.1.1 on 2018-10-19 21:36

from django.db import migrations, models
import review.models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, upload_to=review.models.upload_review_image_path),
        ),
    ]
