# Generated by Django 2.1.1 on 2018-10-21 10:58

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_review_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
    ]
