# Generated by Django 2.1.1 on 2018-10-13 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='complain_type',
            field=models.CharField(choices=[('about service', 'About Service'), ('about book', 'About Book'), ('others', 'Others')], max_length=20),
        ),
    ]
