# Generated by Django 2.1.1 on 2018-10-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20181015_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(choices=[('home delivery', 'Home Delivery'), ('office pick', 'Office Pick')], default='home delivery', max_length=10),
        ),
    ]
