# Generated by Django 2.1.1 on 2018-10-16 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20181016_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(blank=True, choices=[('home delivery', 'Home Delivery'), ('office pick', 'Office Pick')], max_length=100, null=True),
        ),
    ]
