# Generated by Django 2.1.1 on 2018-10-16 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('orders', '0009_auto_20181016_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingmethod',
            name='billing_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.BillingProfile'),
        ),
    ]
