# Generated by Django 2.1.1 on 2018-10-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_shippingmethod_billing_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingmethod',
            name='method',
            field=models.CharField(choices=[('home delivery', 'Home Delivery'), ('office pick', 'Office Pick')], default='home delivery', max_length=100),
        ),
    ]
