# Generated by Django 2.1.1 on 2018-10-24 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_orderitem_item_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart_total',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=9),
        ),
    ]
