# Generated by Django 2.1.1 on 2018-10-16 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_auto_20181016_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookauthor',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, null=True),
        ),
    ]
