# Generated by Django 2.1.1 on 2018-10-16 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0003_auto_20181016_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookauthor',
            name='name',
            field=models.CharField(help_text='Enter Author name', max_length=255, unique=True),
        ),
    ]
