# Generated by Django 2.1.1 on 2018-10-16 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0004_auto_20181016_1149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookauthor',
            options={'ordering': ['name']},
        ),
    ]
